# File parsed by TrlParser -> model_args, training_args, script_args
# CUDA_VISIBLE_DEVICES=0 trl vllm-serve --model Qwen/Qwen2.5-1.5B-Instruct
# accelerate launch --num_processes 1 src/open_r1/grpo.py --config recipes/hypoGen/config_demo.yaml
# Model arguments
model_name_or_path: Qwen/Qwen2.5-1.5B-Instruct
#model_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
#dataset_name: open-r1/OpenR1-Math-220k
dataset_name: Dudep/retweet_all
system_prompt: '''
## Instruction
You are a social media expert. Your task is to generate new hypotheses based on your understanding of tweets and social media.
You will generate hypotheses that are useful for predicting which tweet out of a pair will be retweeted more.
You will not be given the actual tweets, but you need to derive your hypotheses based on your understanding of social media dynamics and user behavior.
'''

# GRPO trainer confsig
bf16: true
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.7
do_eval: false
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen/Qwen2.5-1.5B-Instruct
#hub_model_id: DeepSeek-R1-Distill-Qwen-1.5B-hypogen-GRPO
hub_strategy: every_save
learning_rate: 2.0e-05
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 256
max_completion_length: 256
max_steps: -1
num_generations: 4
num_train_epochs: 1
output_dir: data/Qwen2.5-1.5B-hypogen-GRPO
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
push_to_hub: false
report_to:
- wandb
reward_funcs:
- novelty
- practicality
- soundness
- tag_count
reward_weights:
- 1.0
- 1.0
- 1.0
- 1.0
save_strategy: "epoch"
save_total_limit: 1
seed: 42
warmup_ratio: 0.1